import { Flex } from '@chakra-ui/react';
import Head from 'next/head';
import { FC, ReactNode } from 'react';
import { Footer } from './Footer';
import { Navbar } from './Navbar';

type Props = {
  children?: ReactNode;
};

export const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Storiess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        flexDirection="column"
        height="100%"
        minHeight="100vh"
        position="relative"
        bg="#1a202c"
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </Flex>
    </>
  );
};
